spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url : $(JDBC_DATABASE_URL)
    username: $(JDBC_DATABASE_USERNAME)
    password: $(JDBC_DATABASE_PASSWORD)
    initialization-mode: NEVER
#    driver-class-name: org.postgresql.Driver
#    url : jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: postgres
#    initialization-mode: NEVER
#  cache.type  : redis
#  redis.host : localhost
#  redis.port : 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create 
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: master
server :
     port : 8081
     