spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url : ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: NEVER
#  cache.type  : redis
#  redis.host : localhost
#  redis.port : 6379
  redis.url  : ${REDISCLOUD_URL}
  redis.timeout: 10
  redis:
    jedis:
      pool:
        max-idle: 5
        min-idle: 1
        max-active: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: master
server :
     port : 8080
     
